name: src
description: A new Flutter project.
publish_to: "none"
version: 2.0.1+23

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # apple
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  fl_chart: ^0.67.0
  shared_preferences: ^2.2.2
  pdf: ^3.11.3
  printing: ^5.12.0
  excel: ^2.1.0
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.1

  # Firebase & Google
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.1.3

  #google_mobile_ads: ^5.1.0

  # Utils
  path_provider: ^2.1.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  decimal: ^3.2.1
  intl: ^0.20.2
  share_plus: ^12.0.0
  in_app_review: ^2.0.9

  # Splash
  # flutter_native_splash: 2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon2.png
# flutter_native_splash:
#   color: "#3F51B5" # Arka plan rengi (indigo)
#   android: true
#   ios: false
#   android_gravity: center

